connector:
  toolbox:
    name: toolbox
    type: mcp
    base_url: ${oc.env:TOOLBOX_URL,http://localhost:8001/mcp}
    timeout: 30
    transport: streamable_http
    auth:
      type: token
      key_name: ${oc.env:TOOLBOX_AUTH_HEADER,Authorization}
      key_value: ${oc.env:TOOLBOX_TOKEN,''}

  self:
    name: toolbox
    type: mcp
    base_url: ${connector.toolbox.base_url}
    timeout: 30
    transport: streamable_http
    auth:
      type: none
