import asyncio
from typing import Any, Protocol, runtime_checkable

from agent.domain.model.agent_message_stream import AgentMessageStream


@runtime_checkable
class SSEQueuePort(Protocol):
    @property
    def queue(self) -> asyncio.Queue[AgentMessageStream]: ...

    async def token(self, value: str) -> None: ...
    async def final(self, value: str, metadata: dict[str, Any] | None = None) -> None: ...
    async def error(self, value: str) -> None: ...
    async def complete(self) -> None: ...
