app_configuration:
  env: ${oc.env:APP_ENV,dev}
  run: async

  connector:
    api:
      llm: ${connector.llm}
    file:
      local_fs: ${connector.local_fs}
    database:
      postgres: ${connector.postgres}
      users: ${connector.users}
      checkpointer: ${connector.checkpointer}
    telemetry:
      open_telemetry: ${connector.telemetry}

  operation:
    gpt_oss_20b: ${operation.gpt_oss_20b}
    ministral_3_14b_reasoning: ${operation.ministral_3_14b_reasoning}
    ministral_3_3b: ${operation.ministral_3_3b}
    qwen_3_1p7b: ${operation.qwen_3_1p7b}