application_configuration:
  env: ${oc.env:APP_ENV,debug}
  run: async

  connector:
    api:
      llm: ${connector.llm}
    database:
      checkpointer: ${connector.checkpointer}
      users: ${connector.users}
    telemetry:
      open_telemetry: ${connector.telemetry}
    mcp:
      toolbox: ${connector.toolbox}
      self: ${connector.self}

  operation:
    gpt_oss_20b: ${operation.gpt_oss_20b}
    ministral_3_14b_reasoning: ${operation.ministral_3_14b_reasoning}
    ministral_3_3b: ${operation.ministral_3_3b}
    qwen_3_1p7b: ${operation.qwen_3_1p7b}
