import asyncio
from typing import Protocol, Optional

from agentic.domain.model.agent_message_stream import AgentMessageStream


class SSEQueuePort(Protocol):
    @property
    def queue(self) -> asyncio.Queue[AgentMessageStream]: ...

    async def token(self, value: str) -> None: ...
    async def final(self, value: str, metadata: Optional[dict[str, str]] = None) -> None: ...
    async def error(self, value: str) -> None: ...
    async def complete(self) -> None: ...
