import asyncio
from typing import Protocol


class StreamEventsPort(Protocol):
    @property
    def queue(self) -> asyncio.Queue: ...

    async def token(self, value: str) -> None: ...
    async def final(self, value: str) -> None: ...
    async def error(self, value: str) -> None: ...
    async def complete(self) -> None: ...
