from typing import Protocol, runtime_checkable

from mcp import ClientSession


@runtime_checkable
class McpSessionFactory(Protocol):
    async def start(self) -> None: ...
    async def close(self) -> None: ...
    async def session(self) -> ClientSession: ...
    async def invalidate(self) -> None: ...
