operation:
  gpt_oss_20b:
    name: gpt-oss-20b
    connector: ${connector.llm}
    type: api
    endpoint: /chat/completions
    method: POST
    parameters:
      model: ${operation.gpt_oss_20b.name}
      temperature: 0.0
      max_tokens: 8000

  ministral_3_14b_reasoning:
    name: mistralai/ministral-3-14b-reasoning
    connector: ${connector.llm}
    type: api
    endpoint: /chat/completions
    method: POST
    parameters:
      model: ${operation.ministral_3_14b_reasoning.name}
      temperature: 0.0
      max_tokens: 8000

  ministral_3_3b:
    name: mistralai/ministral-3-3b
    type: api
    connector: ${connector.llm}
    endpoint: /chat/completions
    method: POST
    parameters:
      model: ${operation.ministral_3_3b.name}
      temperature: 0.0
      max_tokens: 8000

  qwen_3_1p7b:
    name: qwen/qwen3-1.7b
    connector: ${connector.llm}
    type: api
    endpoint: /chat/completions
    method: POST
    parameters:
      model: ${operation.qwen_3_1p7b.name}
      temperature: 0.0
      max_tokens: 8000